### PR TITLE
Correct a typo in configs/README.md

### PR DESCRIPTION
**Pull request by felixonmars**
### Issues associated with this PR

Your PR should present related issues you want to solve.

### Sign the CLA
Make sure you have signed the [CLA](https://www.clahub.com/agreements/alipay/sofa-mosn)

### Solutions
You should show your solutions about the issues in your PR, including the overall solutions, 
details and the changes. At this time, Chinese is allowed to describe these.

### UT result
Unit Test is needed if the code is changed, your unit test should cover boundary cases, corner cases, and some exceptional cases.
And you need to show the ut result.

### Benchmark
If your code involves the processing of every request, you should give the Benchmark Result

### Code Style
+ Make sure `Goimports` has run
+ Show `Golint` result

### CODE REVIEW

**Comment by nejisama** [comment]
Please sign CLA

**Comment by felixonmars** [comment]
I already signed, not sure why the bot didn't update here.

**Comment by nejisama** [comment]
> I already signed, not sure why the bot didn't update here.

you can close this pr, and start a new one

**Comment by nejisama** [comment]
> I already signed, not sure why the bot didn't update here.

do not reopen this one,  make a new pull request

**Comment by nejisama** [comment]
this pr still have cla bug. close it .

**Pull request closed without merging**
